### ISSUE TITLE
Support for components using spread operators

### ISSUE THREAD

**Issue by mikesteele** [Polymer/polymer-modulizer#459]
We have some components in our project using spread operators that blow up the upgrade tool.

On running `modulizer --out .`, we see:
```
Unhandled Rejection at: Promise  Promise {
  <rejected> { Error: Line 23: Unexpected token ...
    at ErrorHandler.constructError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5020:27)
    at JSXParser.Parser.unexpectedTokenError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1985:39)
    at JSXParser.Parser.throwUnexpectedToken (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1995:21)
    at JSXParser.Parser.parseObjectPropertyKey (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2492:33)
    at JSXParser.Parser.parseObjectProperty (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2527:25)
    at JSXParser.Parser.parseObjectInitializer (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2595:35)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2278:37)
    at JSXParser.Parser.parsePrimaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2347:38)
    at JSXParser.parsePrimaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:466:97)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2278:37)
    at JSXParser.Parser.parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2892:26)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2278:37)
    at JSXParser.Parser.parseUpdateExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2997:26)
    at JSXParser.Parser.parseUnaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:3041:26)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2278:37)
  index: 745,
  lineNumber: 23,
  description: 'Unexpected token ...' } }  reason:  { Error: Line 23: Unexpected token ...
    at ErrorHandler.constructError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5020:27)
    at JSXParser.Parser.unexpectedTokenError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1985:39)
    at JSXParser.Parser.throwUnexpectedToken (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1995:21)
    at JSXParser.Parser.parseObjectPropertyKey (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2492:33)
    at JSXParser.Parser.parseObjectProperty (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2527:25)
    at JSXParser.Parser.parseObjectInitializer (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2595:35)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2278:37)
    at JSXParser.Parser.parsePrimaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2347:38)
    at JSXParser.parsePrimaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:466:97)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2278:37)
    at JSXParser.Parser.parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2892:26)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2278:37)
    at JSXParser.Parser.parseUpdateExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2997:26)
    at JSXParser.Parser.parseUnaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:3041:26)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2278:37)
  index: 745,
  lineNumber: 23,
  description: 'Unexpected token ...' }

```

**Comment by MrTinyByte** [comment]
I'm having this problem too

**Comment by dsyrstad** [comment]
After having to do modulizer --force with a committed git repo and include --npm-version 1.0.0 (not documented in either the README.md or https://www.polymer-project.org/3.0/docs/upgrade), I also get this error with the spread operator ("...") which I use all over the place. It also doesn't tell you the offending file.

If you use Redux, you're probably using the spread operator.  My Polymer 3 upgrade is dead in the water after only 50 minutes.

Here's the error I'm seeing (not unlike @mikesteele 's):

```
Unhandled Rejection at: Promise  Promise {
  <rejected> { Error: Line 85: Unexpected token ...
    at ErrorHandler.constructError (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5028:27)
    at JSXParser.Parser.unexpectedTokenError (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1985:39)
    at JSXParser.Parser.throwUnexpectedToken (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1995:21)
    at JSXParser.Parser.parseObjectPropertyKey (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2499:33)
    at JSXParser.Parser.parseObjectProperty (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2534:25)
    at JSXParser.Parser.parseObjectInitializer (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2602:35)
    at JSXParser.Parser.inheritCoverGrammar (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2285:37)
    at JSXParser.Parser.parsePrimaryExpression (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2354:38)
    at JSXParser.parsePrimaryExpression (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:466:97)
  index: 3300,
  lineNumber: 85,
  description: 'Unexpected token ...' } }  reason:  { Error: Line 85: Unexpected token ...
    at ErrorHandler.constructError (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5028:27)
    at JSXParser.Parser.unexpectedTokenError (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1985:39)
    at JSXParser.Parser.throwUnexpectedToken (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1995:21)
    at JSXParser.Parser.parseObjectPropertyKey (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2499:33)
    at JSXParser.Parser.parseObjectProperty (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2534:25)
    at JSXParser.Parser.parseObjectInitializer (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2602:35)
    at JSXParser.Parser.inheritCoverGrammar (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2285:37)
    at JSXParser.Parser.parsePrimaryExpression (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2354:38)
    at JSXParser.parsePrimaryExpression (/usr/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:466:97)
  index: 3300,
  lineNumber: 85,
  description: 'Unexpected token ...' }
```
