### ISSUE TITLE
polymer-modulizer error with unhandled rejection : 'unexpected token'

### ISSUE THREAD

**Issue by vtolkanov** [Polymer/polymer-modulizer#463]
I tried to upgrade polymore 2.x project to polymer 3.0. I used polymer-modulizer for this.
But such error occured. Can you help me?

![image](https://user-images.githubusercontent.com/40726938/44458561-fc44f080-a649-11e8-8c06-e8ec370d35b3.png)

**Comment by gabrielsaldana** [comment]
Got a similar output when trying to convert my Polymer 2 app to Polymer 3:

```
modulizer --out .
? npm package version? 2.0
[1/2] 🌀  Converting Package...
Out directory: /Users/gabriel/Documents/projects/axiads
Unhandled Rejection at: Promise  Promise {
  <rejected> { Error: Line 10: Unexpected token ...
    at ErrorHandler.constructError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5028:27)
    at JSXParser.Parser.unexpectedTokenError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1985:39)
    at JSXParser.Parser.throwUnexpectedToken (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1995:21)
    at JSXParser.Parser.parseObjectPropertyKey (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2499:33)
    at JSXParser.Parser.parseObjectProperty (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2534:25)
    at JSXParser.Parser.parseObjectInitializer (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2602:35)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2285:37)
    at JSXParser.Parser.parsePrimaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2354:38)
    at JSXParser.parsePrimaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:466:97)
  index: 214,
  lineNumber: 10,
  description: 'Unexpected token ...' } }  reason:  { Error: Line 10: Unexpected token ...
    at ErrorHandler.constructError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:5028:27)
    at JSXParser.Parser.unexpectedTokenError (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1985:39)
    at JSXParser.Parser.throwUnexpectedToken (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:1995:21)
    at JSXParser.Parser.parseObjectPropertyKey (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2499:33)
    at JSXParser.Parser.parseObjectProperty (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2534:25)
    at JSXParser.Parser.parseObjectInitializer (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2602:35)
    at JSXParser.Parser.inheritCoverGrammar (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2285:37)
    at JSXParser.Parser.parsePrimaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:2354:38)
    at JSXParser.parsePrimaryExpression (/usr/local/lib/node_modules/polymer-modulizer/node_modules/recast/node_modules/esprima/dist/esprima.js:466:97)
  index: 214,
  lineNumber: 10,
  description: 'Unexpected token ...' }
```

**Comment by gabrielsaldana** [comment]
Solved my problem by removing all my javascript files out of the project and only leave polymer elements files. The modulizer ran successfully, then I put my js files back into the project.

**Comment by govis** [comment]
Same error here as well

<pre><code>Unhandled Rejection at: Promise  Promise {
  <rejected> { Error: Line 31: Unexpected token
    at ErrorHandler.constructError (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:5028:27)
    at JSXParser.Parser.throwError (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:1936:34)
    at JSXParser.Parser.parseImportDeclaration (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:4795:19)
    at JSXParser.Parser.parseStatementListItem (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:3373:39)
    at JSXParser.Parser.parseFunctionSourceElements (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:4195:29)
    at JSXParser.Parser.isolateCoverGrammar (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:2269:37)
    at JSXParser.Parser.parsePropertyMethod (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:2441:26)
    at JSXParser.Parser.parsePropertyMethodFunction (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:2458:28)
    at JSXParser.Parser.parseClassElement (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:4628:79) index: 1119, lineNumber: 31, description: 'Unexpected token' } }  reason:  { Error: Line 31: Unexpected token
    at ErrorHandler.constructError (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:5028:27)
    at JSXParser.Parser.throwError (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:1936:34)
    at JSXParser.Parser.parseImportDeclaration (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:4795:19)
    at JSXParser.Parser.parseStatementListItem (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:3373:39)
    at JSXParser.Parser.parseFunctionSourceElements (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:4195:29)
    at JSXParser.Parser.isolateCoverGrammar (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:2269:37)
    at JSXParser.Parser.parsePropertyMethod (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:2441:26)
    at JSXParser.Parser.parsePropertyMethodFunction (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:2458:28)
    at JSXParser.Parser.parseClassElement (C:\Users\govis\AppData\Roaming\npm\node_modules\polymer-modulizer\node_modules\recast\node_modules\esprima\dist\esprima.js:4628:79) index: 1119, lineNumber: 31, description: 'Unexpected token' }</code></pre>

**Comment by govis** [comment]
Same error here as well <code>Unhandled Rejection at: Promise  Promise {
   { Error: Line 31: Unexpected token
    at ErrorHandler.constructError....</code>

It was caused by a Webpack-style import in my case 
<code>import(/* webpackChunkName: "moduleName" */ './moduleName').then(_ => {
... some code here
});</code>

If modulizer told us the source file in question at least that would save a lot of time. Thank you

**Comment by vtolkanov** [comment]
I solved it out by manually upgrading all files. It seems modulizer doesn't work well...

**Comment by web-padawan** [comment]
Same as Polymer/tools#665

**Comment by Spitzbua** [comment]
We also had the unexpected token error when converting our big project. Try to checkout the polymer-modulizer and built it on your own. It seems that the official release does not have all fixes included. Afterwards built it with a command such as that:

> node --max_old_space_size=8096 /mnt/c/Work/Tools/polymer/polymer-modulizer/bin/modulizer.js --npm-version 6.4.1 --out

Just building and running it from scratch fixed my "Unexpected token !" error.
